GET http://localhost:3000/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NTE3NjYzNTAsImV4cCI6MTY4MzMyMzk1MCwiYXVkIjoiZ2VsQG1haWwuY29tIiwiaXNzIjoibXlsb2NhbGhvc3QuY29tIn0.J5Lu5o7NVUDJJi1_iQ6jkLJiNUu5Ip61u2z9jYtztvk
###
GET http://localhost:3000/auth/abc

###
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "name":"Reggie",
  "email": "Reggie@mail.com",
  "password":"qqqqqq",
  "password2":"qqqqqq",
  "terms":true, 
  "loggedIn":true
}
###


POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email":"gel@mail.com",
  "password":"qqqqqq"
}

###
POST http://localhost:3000/auth/refresh-token
Content-Type: application/json

{
  "refreshToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NTE3NjM1MjgsImV4cCI6MTY4MzMyMTEyOCwiYXVkIjoiZ2VsQG1haWwuY29tIiwiaXNzIjoibXlsb2NhbGhvc3QuY29tIn0.ci7n5exFeWjFGzmnWgHesoHEGnzo6-W1fsVC_cH9MKk"
}


###
DELETE http://localhost:3000/auth/logout
Content-Type: application/json

{
  "refreshToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NTE3NjYzNTAsImV4cCI6MTY4MzMyMzk1MCwiYXVkIjoiZ2VsQG1haWwuY29tIiwiaXNzIjoibXlsb2NhbGhvc3QuY29tIn0.ODYaOQ_Fd_WVfUM35GpZnS_g52p7CMmaFfWB3kPzvnk"
}